feat: Expose security database initial credentials
terraform-aws-modules/terraform-aws-redshift pull request #80
Opened 2023-02-26 06:30 UTC by andormarkus

## Description
We are exposing the database credential in the `output.tf` as secure variable thus a randomly generated can be loaded into other places.

## Motivation and Context
Closes #75

2023-03-29 10:28 UTC, andormarkus commented
Up

2023-05-02 12:27 UTC, andormarkus commented
#remove_stale_label
@antonbabenko Please can you review it?

2023-05-02 12:35 UTC, antonbabenko requested changes
Please rename outputs and update the docs to match Terraform's AWS provider schema.

2023-05-02 12:35 UTC, antonbabenko commented on outputs.tf
> +  value       = var.master_username
```suggestion
  value       = try(aws_redshift_cluster.this[0].master_username, "")
```

2023-05-02 12:35 UTC, antonbabenko commented on outputs.tf
> +output "cluster_username" {
```suggestion
output "master_username" {
```

2023-06-12 00:26 UTC, closed without merging