add managed secrets option
terraform-aws-modules/terraform-aws-redshift pull request #87
Opened 2023-11-10 20:57 UTC by nimish

## Description
Adds the [`manage_master_password`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_cluster#manage_master_password) option to the redshift cluster
## Motivation and Context

Reduces burden to manage secrets by having Redshift manage it directly.
## Breaking Changes

No
## How Has This Been Tested?
- [ x ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ x ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [ x ] I have executed `pre-commit run -a` on my pull request

- [ x ] I have used this in a production upgrade of a redshift cluster

2023-11-10 21:21 UTC, bryantbiggs requested changes

2023-11-10 21:21 UTC, bryantbiggs commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/terraform,macos,intellij+all,visualstudiocode
Please revert the changes to this file

2023-11-10 21:21 UTC, bryantbiggs commented on examples/complete/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
Please remove this file - it should be ignored by the correct `.gitignore` file

2023-11-10 21:21 UTC, bryantbiggs commented on versions.tf
> +  required_version = "~> 1.1"
Revert this line change

2023-11-10 21:21 UTC, bryantbiggs commented on versions.tf
> +      version = "~> 5.25"
```suggestion
      version = ">= 5.24"
```

2023-11-10 21:21 UTC, bryantbiggs commented on versions.tf
> +      version = "~> 3"
revert this line change

2023-11-12 04:26 UTC, nimish commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/terraform,macos,intellij+all,visualstudiocode
done

2023-11-12 18:56 UTC, nimish commented on versions.tf
> +      version = "~> 3"
done

2023-11-12 18:56 UTC, nimish commented on versions.tf
> +      version = "~> 5.25"
done

2023-11-12 18:56 UTC, nimish commented on versions.tf
> +  required_version = "~> 1.1"
done

2024-01-11 18:59 UTC, delaskoff commented
Hi! Any chance to merge?

2024-01-11 20:21 UTC, bryantbiggs approved these changes
thank you!

2024-01-11 20:21 UTC, merged

2024-01-12 22:13 UTC, bryantbiggs commented
hmmm, not sure why the autorelease isn't detecting it as a new release. @antonbabenko what do we do for this scenario?

2024-01-13 21:31 UTC, antonbabenko commented
This PR is included in version 5.1.0 :tada:

2024-01-13 21:37 UTC, antonbabenko commented
@bryantbiggs Looking at commits - https://github.com/terraform-aws-modules/terraform-aws-redshift/commits/master/

This PR was merged with the wrong commit title (commit 173b49322fb2ffa6eb51101a05a838500e5174c9). It should be "feat: ...", "fix: ...", so that Release GH Action does the work.

Looking in the previous commits, there was also 9c90d530e29db578f9e7bf65b82dbefd92b1fc6b which was ignored by the Release GH Action.